### ISSUE TITLE
Create new election procedure

### ISSUE THREAD

**Issue by paregorios** [epigraphy-info/committee-tasks#4]
Task Breakdown:

- [ ] Prepare text and ask for candidates
- [ ] Send to the mailing list
- [ ] Establish electronic voting mechanism for future committee elections

**Comment by vrazanajao** [comment]
Here is the link to the draft of the circular to be sent for the Call for nomination for the Steering Committee: https://docs.google.com/document/d/14g41VUuaAt77aQarZVA6XCDB4jQfK0chtIeqDjCZYOg/edit?usp=sharing
